#!/bin/sh
# @author Ralf Habacker
#
# trigger osc token by grep like pattern
#

if test -z "$1"; then
    echo $0 [--dry-run] <grep-like-pattern-in-osc-token-list>
    exit 1
fi

if test "$1" == "--dry-run"; then
    run=echo
    shift
fi

for i in $(osc token | grep $1 | sed 's,^.*string=",,g;s,".*$,,g'); do
    $run osc token --trigger=$i
done