#!/bin/sh
# @author Ralf Habacker
#
# trigger osc token by grep like pattern
#

if test "$1" == "--dry-run"; then
    run=echo
    shift
fi

if test -z "$1"; then
    echo "$0 [--dry-run] <gawk regex for project names> <gawk regex for package names>"
    exit 1
fi

for i in $(osc token | gawk '$1 ~ /ID/ { id = $3 } $1 ~ /String/ { str = $3 } $1 ~ /^Project/ && $3 ~ project { p=1 } $1 ~ /^Package/ && $3 ~ package { print str }' project=$1 package=$2); do
    n=$($run osc token --trigger=$i | gawk '$0 ~ /status code/ { print $0 }')
    echo "$i $n"
done