#!/bin/sh

# 
# trigger obs if git commit id changes
#
# @author Ralf Habacker <ralf.habacker@freenet.de>
#

r=$(realpath $0)
r=$(dirname $r)
bn=$(basename $0)

trigger_obs() {
    for token in $*; do
        $run curl -s -H "Authorization: Token $token" -X POST https://api.opensuse.org/trigger/runservice
    done
}

file_name() {
    echo /tmp/$bn-$(echo $url-$branch | sed 's,[/:@],-,g')
}

check_package() {
    url=$1
    branch=$2
    obstoken=$3
    id=$(git ls-remote $url refs/heads/$branch | sed 's,\s.*$,,g')
    file=$(file_name)
    oldid=
    if ! test -f "$file"; then
        echo $id > "$file"
        trigger_obs $obstokens
        return
    fi

    oldid=$(cat "$file")

    if test "$id" == "$oldid"; then
        return
    fi 
    trigger_obs $obstokens
    echo $id > "$file"
}

run=
clean=0

for arg in "$@"
do
    case "$arg" in
        --dry-run)
            run=echo
            ;;
        --clean)
            clean=1
            ;;
    esac
done

while read i; do
    url=""
    eval "$i"
    if test -n "$url"; then
        if test "$clean" -eq 1; then
            rm -f $(file_name)
        else
            check_package $url $branch "$obstokens"
        fi
    fi
done < $r/../conf/$bn.conf
